Improved build process and unit test system
mosa/MOSA-Project pull request #1067
Opened 2023-06-23 06:50 UTC by tgiphil

2023-06-23 20:18 UTC, tgiphil commented
Added additional functional and unit tests to the build process. Unfortunately, Qemu does not always launch the VM properly and fails. When this happens, the GitHub failed action tasks need to be re-tried.

2023-06-24 02:02 UTC, charsleysa requested changes

2023-06-24 02:02 UTC, charsleysa commented on Source/Mosa.Utility.UnitTests/UnitTestEngine.cs
> +			Thread.Sleep(10);
Is this fine hard-coded?

2023-06-24 02:02 UTC, charsleysa commented on Source/Mosa.Utility.UnitTests/UnitTestEngine.cs
> +			Thread.Sleep(10);
Is this fine hard-coded?

2023-06-24 09:04 UTC, charsleysa approved these changes
LGTM

2023-06-24 19:16 UTC, merged