Remove old kernel, improved unit tests speed, and more!
mosa/MOSA-Project pull request #1124
Opened 2023-08-15 15:39 UTC by AnErrupTion

- Ported TestWorld as a BareBones kernel
- Removed Mosa.UnitTests.x86 and Mosa.Kernel.x86 projects
- Fixed Mosa.Kernel.BareMetal.x86.DebugWrite to always write to COM2
- Considerably improved the speed of unit tests by not outputting anything to the invisible console
- Made the template use the BareMetal kernel
- Updated documentation to reflect all the changes
- Fixed BareMetal x86 unit test runner
- Added output message when running the disassemblers

2023-08-16 03:15 UTC, charsleysa commented
There's a bug somewhere, the unit tests are consistently timing out for optimization level 2, 3, and 4 on all platforms.

2023-08-16 05:54 UTC, tgiphil requested changes

2023-08-16 05:54 UTC, tgiphil commented on Source/Docs/demos.rst
> +The **TestWorld** demo is a barebones demo meant to show how you can create a barebones kernel using MOSA.
Let's discuss demo name. Also, barebones is minimalistic wording. Let's use our mission statement: "As operating systems share a lot of common groundwork, MOSA aims to standardize interfaces in order to foster portability and to provide both projects with basic implementations of these interfaces." to guide as.

2023-08-16 05:54 UTC, tgiphil commented on Source/Mosa.BareBones.TestWorld.x86/Mosa.BareBones.TestWorld.x86.csproj
> -			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
Need this. It's our one test of this functionality.

2023-08-16 05:54 UTC, tgiphil commented on Source/Mosa.Kernel.BareMetal/Serial.cs
Where did this go?

2023-08-16 05:54 UTC, tgiphil commented on Source/Mosa.Linux.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Mosa.BareBones.TestWorld.x86", "Mosa.BareBones.TestWorld.x86\Mosa.BareBones.TestWorld.x86.csproj", "{577B8294-334B-4E02-BE1A-CBA8ABAF8939}"
DM

2023-08-16 05:54 UTC, tgiphil commented on Source/Mosa.UnitTests.BareMetal.x86/UnitTestEngine.cs
> +	private static void SendByte(byte b) => Platform.Serial.Write(ComPort, b);
Let's proxy this thru the Serial instead of directly to the Platform API.

2023-08-19 18:16 UTC, AnErrupTion commented
- Fixed Sparse Conditional Constant Propagation bug with sign/zero extensions (thanks @tgiphil!)

2023-08-19 18:25 UTC, tgiphil commented on Source/Mosa.Compiler.Framework/Analysis/SparseConditionalConstantPropagation.cs
> +			result = (operand1 & 0x80) == 0 ? operand1 : operand1 | 0xFFFFFF00;
Needs to be input value needs to be truncated first. 

Same issue with below.

2023-08-27 16:34 UTC, tgiphil commented
Please re-base. Most changes should already be incorporated.

2023-09-01 15:08 UTC, tgiphil commented
Given the number of file changes since this pull request, let's reopen this after it has been rebased.

2023-09-01 15:08 UTC, closed without merging