Add Limine bootloader (closes #973)
mosa/MOSA-Project pull request #974
Opened 2022-04-12 20:16 UTC by AnErrupTion

This PR adds the Limine bootloader!
Note: The ``limine-deploy`` tool has been ported to a single C# class to avoid using external tools!

2022-04-13 02:26 UTC, tgiphil requested changes

2022-04-13 02:26 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		private static byte[] bootloader_img = {
Include the binary as resource instead.

2022-04-13 02:26 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +			WritePtr(&stage2SizeA, 0x1a4, sizeof(ushort));
No unsafe code! 

See Mosa.Utility.BootImage\Syslinux.cs and Generator.cs as examples. 

Note: We are not supporting big endian (all the code to do that was removed a few years ago).

2022-04-13 02:26 UTC, tgiphil commented on Source/Mosa.Utility.Launcher/Builder.cs
> +			if (LauncherSettings.ImageBootLoader.StartsWith("syslinux"))
Let's be exact and use a switch/case.

2022-04-13 02:26 UTC, tgiphil commented on Tools/limine/limine.cfg
> +TIMEOUT=5
Future. Let's create the config file within Starter.cs so it can be customized later.

2022-04-15 21:44 UTC, tgiphil requested changes

2022-04-15 21:44 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		private static unsafe void WritePtr(void* _buffer, ulong loc, ulong count)
Unsafe code!

2022-04-15 21:44 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		private static byte[] bootloader_img = {
Include the binary as resource instead.

2022-04-15 22:12 UTC, tgiphil requested changes

2022-04-15 22:12 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		private static byte[] bootloader_img = {
Include the binary as resource instead.

2022-04-15 22:12 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		public static unsafe void Deploy(string path)
Unsafe code!

2022-04-15 22:12 UTC, tgiphil commented on Source/Mosa.Utility.BootImage/Limine.cs
> +		private static unsafe void WritePtr(void* _buffer, ulong loc, ulong count)
Unsafe code!

2022-04-15 22:12 UTC, charsleysa approved these changes
LGTM

2022-04-15 22:25 UTC, merged